name: 'Remove Old Packages'
description: 'Remove Old Packages of GHCR.IO of repository'
inputs:
  packageName:  # id of input
    description: 'Package Name'
    required: true
    default: 'Set By Github'
  packageType:
    description: 'Package Type'
    required: true
    default: 'container'
  org:  # id of input
    description: 'Organization'
    required: true
    default: 'Set By Github'
  myToken:  # id of input
    description: 'Token Github'
    required: true
    default: 'Set By Github'
  nbToKeep:  # id of input
    description: 'Number of versions to keep'
    required: true
    default: '3'
  tagsToKeep:  # id of input
    description: 'Protected tags'
    required: true
    default: 'latest, build, stable'

runs:
  using: 'node12'
  main: 'index.js'
